name: Build Python Package

on:
  pull_request:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-dev libboost-filesystem-dev libboost-system-dev \
          libboost-thread-dev rapidjson-dev libsnappy-dev zlib1g-dev \
          liblz4-dev libzstd-dev

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


  build:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup Wheel Twine
        run: |
          pip install setuptools wheel twine

      - name: Increment Version
        run: |
          python version_handler.py

      - name: Commit and push version bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version.py  # Adjust if you use setup.cfg
          git commit -m "Bump version to new release"
          git push

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
